<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracionReglasRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ConfiguracionReglasRepository extends EntityRepository
{


}
